version: '3.8'  # You can use other versions compatible with Docker

services:
  # db:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: always

  mediafusion:
    build:
      # context: ./apps/MediaFusion
      context: .
      dockerfile: ./apps/MediaFusion/Dockerfile
    container_name: media-fusion
    ports:
      - "3006:3000"
    env_file:
      - ./.env

  images:
    build:
      # context: ./apps/MediaFusion
      context: .
      dockerfile: ./apps/images/Dockerfile
    container_name: images
    ports:
      - "3001:3000"
    depends_on:
      - mediafusion
    env_file:
      - ./.env

  # videos:
  #   build:
  #     # context: ./apps/MediaFusion
  #     context: .
  #     dockerfile: ./apps/videos/Dockerfile
  #   container_name: videos
  #   ports:
  #     - "3002:3000"
  #   depends_on:
  #     - mediafusion
  #   env_file:
  #     - ./.env

  # audio:
  #   build:
  #     # context: ./apps/MediaFusion
  #     context: .
  #     dockerfile: ./apps/audio/Dockerfile
  #   container_name: audio
  #   ports:
  #     - "3003:3000"
  #   depends_on:
  #     - mediafusion
  #   env_file:
  #     - ./.env

volumes:
  postgres_data:
    driver: local

networks:
  my-network:
    driver: bridge
